defaults:
  - data
  - interpolant
  - model
  - experiment
  - _self_
  
# override/add the following config entries
data:

  module:
    inference_only_mode: True
    loaders:                                # DataLoader class
      num_workers: 1                       # per dataloader (one dataloader per GPU, train, val and test)
      prefetch_factor: 10             # number of batches to prefetch

  dataset:
    predict:
        num_samples: 100          # number of samples to generate for each input sequence
        csv_path: metadata/latest_test_val_metadata.csv
        pred_sampler:
          batch_size: 25

    # train_val_test_pdbs:                    # common filters for train/val/test set
    #   csv_path: metadata/ABB3_latest_CDRsim_metadata_random_ceph_paths.csv
  
interpolant:
  sampling:
    num_timesteps: 100
               
experiment:
  num_devices: 1 #4
  prediction:
    save_traj: False
    save_int_traj: False # False
    output_dir: predictions/
    ckpt_path: ckpt/abb4_STEROIDS/abb4_STEROIDS.ckpt

  checkpointer:
    dirpath: ckpt/${experiment.wandb.project}/${experiment.wandb.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    save_last: True
    save_top_k: 5 #10
    # every_n_train_steps: 1
    every_n_epochs: null
    save_on_train_epoch_end: False
    monitor: valid/h_cdr3_d_mean_rmsd_sims
    mode: min
