defaults:
  - data
  - interpolant
  - model
  - experiment
  - _self_
  
# override/add the following config entries
data:

  module:
    inference_only_mode: True
    loaders:                                # DataLoader class
      num_workers: 10                       # per dataloader (one dataloader per GPU, train, val and test)
      prefetch_factor: 10             # number of batches to prefetch

  dataset:
    predict:
        num_samples: 10  # 250        # number of samples to generate for each input sequence
        csv_path: data/example_input.csv
        pred_sampler:
          batch_size: 100

interpolant:
  load_dataset_csv: False
  csv_path: null
  max_resolution: null
  sampling:
    num_timesteps: 100
               
experiment:
  num_devices: 1 #4
  prediction:
    save_traj: False
    save_int_traj: False # False
    output_dir: predictions/
    ckpt_path: ckpt/abb4_STEROIDS/abb4_STEROIDS.ckpt
