defaults:
  - data
  - interpolant
  - model
  - experiment
  - _self_

experiment:                                 # ModelRun, FlowModule classes
  num_devices: 4                            # max number of GPUs to use, if available
  warm_start: null                          # path to checkpoint to test (required)
  debug: False

  checkpointer:
    dirpath: null                           # filled from warm_start checkpoint dir

  validation:
    save_traj: False
    save_int_traj: False

  testing:                                  # FlowModule class
    ckpt_name: last.ckpt                    # checkpoint filename in checkpointer.dirpath
    step_validation: True
    sample_validation: True                 # validation by sampling entire trajectory
    extra_validation: False
    save_sampled_strucs: False

  prediction:
    save_traj: null
    save_int_traj: null
    output_dir: null
    ckpt_path: null


data:
  dataset:                                  # {Train, Length, Fasta, Pdb}Dataset, Distributed{Train, Inference}BatchSampler classes
    train_val_test_pdbs:                    # common filters for train/val/test set
      csv_path: null
    test:
      gen_extent: ${data.gen_extent}
      gen_regions: ${data.gen_regions}

      trainlike: True                      # run train-like loss computation at test time
      trainlike_sampler:                   # DistributedTrainBatchSampler class
        batch_size: 10
        shuffle: False
        num_struc_samples: null
        drop_last: False

      inferencelike: False                  # run inference-like de novo generation and compute metrics at test time
      inferencelike_sampler:               # DistributedInferenceBatchSampler class
        batch_size: 1                      # choose as high as GPU RAM allows
        shuffle: False

interpolant:
  sampling:
    num_timesteps: 100
  rots:
    sample_schedule: linear
  trans:
    sample_schedule: linear
